### PR TITLE
Trait with lifetime

### LINKED ISSUE #53: Docs not embedded for traits anymore
Ex. for gio `cargo build --features "embed-lgpl-docs"` in file auto/settings_backend.rs functions in `pub trait SettingsBackendExt: 'static` not updated despite docs present.

```
<!-- trait SettingsBackendExt::fn path_writable_changed -->
Signals that the writability of all keys below a given path may have
changed.
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #53.

cc @EPashkin (just look at the second commit)

### CODE REVIEW

**Comment by EPashkin** [comment]
Other case seems not covered
```
impl<O: IsA<Action>> ActionExt for O {
    fn activate(&self, parameter: Option<&glib::Variant>) {
```
```
<!-- trait ActionExt::fn activate -->
Activates the action.
```

**Comment by EPashkin** [comment]
Sorry, if implementation,
Thanks and 👍

**Comment by EPashkin** [comment]
*it was implementation

**Comment by EPashkin** [comment]
Seems signals not updated for impl's
Ex. in gdk after signal docs moved to impl
```diff
 the Y coordinate of the destination.
-<!-- trait DeviceExt::fn connect_changed -->
+<!-- impl Device::fn connect_changed -->
 The ::changed signal is emitted either when the `Device`
 has changed the number of either axes or keys. For example
```

**Comment by GuillaumeGomez** [comment]
You mean it's coming from rustdoc-stripper or do we have a bug somewhere else?

**Comment by EPashkin** [comment]
As is wrote in `vendor.cs` same way as others nearby seems it `rustdoc-stripper` bug or some in text typo,  which I don't see.
Also see https://github.com/GuillaumeGomez/rustdoc-stripper/issues/53#issuecomment-504724993

**Comment by GuillaumeGomez** [comment]
For the missing manual docs, it's not because of rustdoc-stripper. But this bug might however I don't understand what's wrong exactly. What do you mean by "signals not updated for impl's"?

**Comment by EPashkin** [comment]
Docs just don't added to code on embedding: even docs seems defined in same way.
result gdk/auto/device.rs
```
impl Device {
    ...
    /// Determines information about the current keyboard grab.
    /// This is not public API and must not be used by applications.
    /// ...
    #[cfg_attr(feature = "v3_16", deprecated)]
    pub fn grab_info_libgtk_only(display: &Display, device: &Device) -> Option<(Window, bool)> {
        skip_assert_initialized!();
        unsafe {
            let mut grab_window = ptr::null_mut();
            let mut owner_events = mem::uninitialized();
            let ret = from_glib(gdk_sys::gdk_device_grab_info_libgtk_only(
                display.to_glib_none().0,
                device.to_glib_none().0,
                &mut grab_window,
                &mut owner_events,
            ));
            if ret {
                Some((from_glib_none(grab_window), from_glib(owner_events)))
            } else {
                None
            }
        }
    }

    pub fn connect_changed<F: Fn(&Device) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn changed_trampoline<F: Fn(&Device) + 'static>(
            this: *mut gdk_sys::GdkDevice,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"changed\0".as_ptr() as *const _,
                Some(transmute(changed_trampoline::<F> as usize)),
                Box_::into_raw(f),
            )
        }
    }
```
vendor.md
```
<!-- impl Device::fn grab_info_libgtk_only -->
Determines information about the current keyboard grab.
This is not public API and must not be used by applications.
...
<!-- impl Device::fn connect_changed -->
The ::changed signal is emitted either when the `Device`
has changed the number of either axes or keys. For example
...
```

**Comment by GuillaumeGomez** [comment]
Then that's a new bug, awesome! You even provided a test case, that'll make my life simpler. Thanks! :)

**Pull request merged**
