### PR TITLE
Add new test

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
@EPashkin The case you gave me seems to work just fine?

### CODE REVIEW

**Comment by EPashkin** [comment]
But it not works on real file in gdk.

**Comment by GuillaumeGomez** [comment]
That doesn't make any sense. :-/

**Comment by EPashkin** [comment]
Maybe something with code length again

**Comment by GuillaumeGomez** [comment]
Maybe... Let's check with full file. :)

**Comment by GuillaumeGomez** [comment]
@EPashkin A few differences in the generated markdown file. Take a look. When we generate those files, we might not do it with last version. That's where the problem is.

**Comment by EPashkin** [comment]
@GuillaumeGomez, `get_basic10_md` don't contains nor `<!-- trait DeviceExt::fn connect_changed -->` (it was after your https://github.com/gtk-rs/lgpl-docs/pull/60) nor `<!-- impl Device::fn connect_changed -->` that added by my https://github.com/gtk-rs/lgpl-docs/pull/61

**Comment by GuillaumeGomez** [comment]
I think the problem comes from the markdown files. Their generation seems to be ok so I don't understand what I'm missing...

**Comment by EPashkin** [comment]
If on clear or embedded device.rs remove `grab_info_libgtk_only` then docs for `connect_changed` is generated, but for `connect_tool_changed` is not.
If remove all functions before them, also only `connect_changed` is generated,
but if swap functions, only `connect_tool_changed` is generated.

**Comment by GuillaumeGomez** [comment]
The other thing is that when generated, `connect_changed` is put inside `DeviceExt`, whereas it should be inside `impl Device`.

**Comment by GuillaumeGomez** [comment]
Oh! The disguised children issue must not have been fixed for doc generation! That's why!

**Comment by GuillaumeGomez** [comment]
We can close this then thanks to https://github.com/gtk-rs/gir/pull/800

**Comment by EPashkin** [comment]
@GuillaumeGomez, seems problem with ignore_macros = true
https://gist.github.com/EPashkin/ae6a9100a7360cc062e421876617f6ab

**Comment by EPashkin** [comment]
No we can't close this

**Comment by GuillaumeGomez** [comment]
Ah?

**Comment by EPashkin** [comment]
Because test better added and 2 failed fixed

**Comment by GuillaumeGomez** [comment]
In here I didn't fix anything, just added a test. Aren't you referring to another PR? #54 perhaps?

**Comment by EPashkin** [comment]
I refer 2 failing test that I wrote in https://github.com/GuillaumeGomez/rustdoc-stripper/pull/55#issuecomment-504784319

**Comment by GuillaumeGomez** [comment]
But id doesn't fail, that's the thing. :-/ The markdown file is invalid.

**Comment by EPashkin** [comment]
Markdown file is valid, rustdoc_stripper don't generate half comment when `regenerate_doc_comments` called with `ignore_macros=true`

**Comment by GuillaumeGomez** [comment]
Oh, so the problem comes whit `ignore_macro`. That I can check. :)

**Comment by GuillaumeGomez** [comment]
I set `ignore_macro` to `true` and it still works. :-/

**Comment by EPashkin** [comment]
Please use my short data from gist

**Comment by GuillaumeGomez** [comment]
Will take a look tomorrow then. It's been a long day... Thanks a lot for your help!

**Comment by EPashkin** [comment]
Good night, I need go to sleep too.

**Comment by GuillaumeGomez** [comment]
@EPashkin Seems to be fixed.

**Comment by EPashkin** [comment]
Not fully 😢: `connect_tool_changed` still not generated,
I updated https://gist.github.com/EPashkin/ae6a9100a7360cc062e421876617f6ab for sample, but not sure if it right (strip failed too).
And https://github.com/GuillaumeGomez/rustdoc-stripper/issues/53#issuecomment-504724993 still same too. Sorry I don't have time today to prepare more test cases.

**Comment by GuillaumeGomez** [comment]
@EPashkin Thanks to you, I was able to find a lot f bugs! I'm just super happy. :D Thanks a lot @EPashkin !

**Comment by GuillaumeGomez** [comment]
Forgot to push test last time...

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, now all xxExt have docs.

**Comment by GuillaumeGomez** [comment]
Then here we go!

**Pull request merged**
