### PR TITLE
Add file_comment test and partial fixes

### PR DESCRIPTION
**Pull request by gkoz**
File comments don't seem to work correctly still

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It seems file comment regeneration is still incomplete.

**Comment by gkoz** [comment]
This still is a problem.

**Comment by gkoz** [comment]
Rebased. I don't see what sort of old interface the test could be targeting.

**Comment by GuillaumeGomez** [comment]
I fixed the issue. Take a look at the last commit I made over yours.

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
