### PR TITLE
Big pr

### LINKED ISSUE #2: Use "common" format to generate comments file
For now, this is a custom format. Very useful and short, but maybe another one could fit this just as good.

### LINKED ISSUE #12: Remove '///' and indentation
It should set them back once we regenerate doc comments.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz 

Fixes #12 
Fixes #2

### CODE REVIEW

**Comment by gkoz** [comment]
This might be the beast occasion to retire `stripper_interface` and instead of `FILE`, `FILE_COMMENT` constants export complete metadata-writing functions like

```
writeln!(out_file, "{}{}{}", FILE, path, END_INFO)
```

so the generator would have to know about the format but just call the functions.

**Comment by GuillaumeGomez** [comment]
I thought about it but wasn't sure it was a good thing (there is the "issue" with ignore macro parameter that forces me to make the difference between `{}` and `{:?}`).

**Comment by gkoz** [comment]
The whitespace eater is too aggressive:
```
/// gtk_show_about_dialog (NULL,
///                        "program-name", "ExampleCode",
///                        "logo", example_logo,
///                        "title" _("About ExampleCode"),
///                        NULL);
```
becomes
```
gtk_show_about_dialog (NULL,
"program-name", "ExampleCode",
"logo", example_logo,
"title" _("About ExampleCode"),
NULL);
```

**Comment by GuillaumeGomez** [comment]
Hum... I was pretty sure the `trim_left` function applied until `///`, I should check it or maybe even right a personal `trim_left` to be sure it won't go crazy.

**Comment by GuillaumeGomez** [comment]
@gkoz: This PR seems to be done. A last look before I merge please?

**Comment by gkoz** [comment]
It looks like the whitespace issue has been fixed but testing on big codebase is difficult because of the panic I mentioned on IRC

**Comment by GuillaumeGomez** [comment]
Okay, I'll merge for now, remove the external dependency of `stripper-interface` and then try to fix this.

**Pull request merged**
