### PR TITLE
Fix invalid comment regeneration

### LINKED ISSUE #40: Incomplete ignore_if_doc_commented implementation
Looks like #39 was not enough. This patch makes the test fail:

```diff
diff --git a/tests/tests.rs b/tests/tests.rs
index 2aecca5..94b4de8 100644
--- a/tests/tests.rs
+++ b/tests/tests.rs
@@ -378,12 +378,22 @@ another
 const BASIC6 : &'static str = r#"/// not stripped comment
 struct Foo;
 
+impl Foo {
+    /// another existing comment
+    fn new() -> Foo { }
+}
+
 struct Bar;
 "#;
 
 const BASIC6_REGEN : &'static str = r#"/// not stripped comment
 struct Foo;
 
+impl Foo {
+    /// another existing comment
+    fn new() -> Foo { }
+}
+
 /// struct Bar comment
 struct Bar;
 "#;
@@ -392,6 +402,8 @@ fn get_basic6_md(file: &str) -> String {
     format!(r#"<!-- file {} -->
 <!-- struct Foo -->
 struct Foo comment
+<!-- impl Foo::fn new -->
+fn new comment
 <!-- struct Bar -->
 struct Bar comment
 "#, file)
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #40.

cc @gkoz

### CODE REVIEW

**Comment by gkoz** [comment]
Looks like my test was not life-like enough, it still misbehaves with `pub unsafe fn new()`.

**Comment by GuillaumeGomez** [comment]
Then please give me the smallest code sample which has the error.

**Comment by gkoz** [comment]
```rust
/// not stripped comment
struct Foo;

impl Foo {
    /// another existing comment
    pub unsafe fn new() -> Foo {}
}

/// struct Bar comment
struct Bar;
```

**Comment by GuillaumeGomez** [comment]
I tested with this fix and it worked. So...?

**Comment by gkoz** [comment]
Interesting. What does this script say?

```bash
#!/bin/sh

set -e
mkdir repro

cat > repro/test.rs <<X
impl Foo {
    /// existing comment
    pub unsafe fn new() -> Foo { }
}
X

cat > repro/docs.md <<X
<!-- file test.rs -->
<!-- impl Foo::fn new -->
bad comment
X

cargo run -- -g -x -d repro -o repro/docs.md
grep bad repro/test.rs
```

**Comment by GuillaumeGomez** [comment]
Interesting indeed. How the tests can pass then?

**Comment by GuillaumeGomez** [comment]
And now @gkoz?

**Comment by gkoz** [comment]
Seems to be doing the right thing now.

**Comment by gkoz** [comment]
We probably don't want the printlns to remain?

**Comment by GuillaumeGomez** [comment]
Oh right sorry. I forgot to remove them. ><

**Pull request merged**
